#### Acceso a elementos de un array

In [51]:
import numpy as np
mi_array = np.arange(100).reshape(10,10)
mi_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mi_array[0,2]# filas, columnas

2

In [55]:
# slicing
mi_array[1:4] # filas

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [56]:
mi_array[1:4,0:2] # filas, columnas

array([[10, 11],
       [20, 21],
       [30, 31]])

In [1]:
mi_array[0:6:2] # filas - salto de dos

NameError: name 'mi_array' is not defined

In [4]:
mi_array[::-1] # recorre las filas de -1 en -1

NameError: name 'mi_array' is not defined

In [5]:
mi_array[:,::-1] # recorre las columnas de -1 en -1

NameError: name 'mi_array' is not defined

In [66]:
mi_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [63]:

# podemos usar una lista para 
# especificar que elementos queremos
mi_array[:,[0,2,8,9]]

array([[ 0,  2,  8,  9],
       [10, 12, 18, 19],
       [20, 22, 28, 29],
       [30, 32, 38, 39],
       [40, 42, 48, 49],
       [50, 52, 58, 59],
       [60, 62, 68, 69],
       [70, 72, 78, 79],
       [80, 82, 88, 89],
       [90, 92, 98, 99]])

In [64]:
#  podemos poner numeros negativos como indice
print(mi_array[-1]) # ultima fila
print(mi_array[-2]) # penutima fila

[90 91 92 93 94 95 96 97 98 99]
[80 81 82 83 84 85 86 87 88 89]


#### Mascaras Booleanas

In [67]:
otro_array = np.arange(10)
otro_array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# Si aplicamos una sentencia logica en numpy
# numpy nos devuelve que elementos del array
# cumplen con la condicion
otro_array > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [69]:
# A un numpy array podemos pasarle una serie de booleanos
# para filtrar los elementos del array
otro_array[otro_array > 5] # nos devuelve los elementos que cumplen la condicion

array([6, 7, 8, 9])

In [78]:
' Como podemos usar esto? '
inventario = np.array(["lavadora", "freidora", "sarten", "batidora"])
precio = np.array([200, 120, 50, 75])
inventario[precio > 100]

<class 'numpy.ndarray'>


In [71]:
# Con listas es mas complicado hacer esto mismo
mi_lista = []
for i in range(len(precio)):
    if precio[i] > 100:
        mi_lista.append(inventario[i])

print(mi_lista)

['lavadora', 'freidora']


#### Compresion de lista

In [72]:
# con arrays usamos mascaras
otro_array = np.arange(10)
otro_array[otro_array > 5]

array([6, 7, 8, 9])

In [79]:
# con listas podemos usar la sintaxis de compresion
numeros = [0,1,2,3,4,5,6,7,8,9]
nueva_lista = [numero for numero in numeros if numero > 5]
print("nueva lista", nueva_lista)

[6, 7, 8, 9]


In [ ]:
# y esa compresion extendida seria...
numeros = np.array([0,1,2,3,4,5,6,7,8,9])
nueva_lista = []
for numero in numeros:
    if numero > 5:
        nueva_lista.append(numero)
nueva_lista